import { useSelector } from "react-redux";
import { type RootState } from "~/redux/store";

export function useSFHObject() {
  const state = useSelector((state: RootState) => state.singleFamily);
  const output = {
    address: state.address,
    price: state.price,
    interest: state.interest,
    downPaymentPerc: state.downPaymentPerc,
    downPaymentDoll: state.downPaymentDoll,
    closingCostsPerc: state.closingCostsPerc,
    closingCostsDoll: state.closingCostsDoll,
    loanTerm: state.loanTerm,
    loanType: state.loanType,
    repairs: state.repairs,
    ARV: state.ARV,
    taxes: state.taxes,
    insurance: state.insurance,
    hoa: state.hoa,
    vacancy: state.vacancy,
    capEx: state.capEx,
    rennovations: state.rennovations,
    maintenance: state.maintenance,
    management: state.management,
    expOther: state.expOther,
    rents: state.rents,
    incOther: state.incOther,
    appreciation: state.appreciation,
    loanBalance: state.loanBalance,
    costOfRenno: state.costOfRenno,
    totalAquisitionReturn: state.totalAquisitionReturn,
    aquisitionCosts: state.aquisitionCosts,
    equity: state.equity,
    LTV: state.LTV,
    mortgagePayment: state.mortgagePayment,
    cashFlow: state.cashFlow,
    expenses: state.expenses,
    monthlyPayment: state.monthlyPayment,
    cashOnCash: state.cashOnCash,
    rennoEquity: state.rennoEquity,
    rennoReturn: state.rennoReturn,
    closingCosts: state.closingCosts,
    capRate: state.capRate,
    ROE: state.ROE,
    ROI: state.ROI,
    fixed: state.fixed,
  };
  return output;
}
