import { SignInButton, UserButton, useUser } from "@clerk/nextjs";
import Head from "next/head";
import Link from "next/link";

export default function Page({ children }: { children: React.ReactNode }) {
  const user = useUser();

  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <nav className="flex">
        <div className="logo-container flex flex-none">
          <img className="logo"></img>
        </div>
        <div className="std-navigation flex flex-1 justify-around">
          <Link href="/about">home</Link>
          <Link href="blog">blog</Link>
        </div>
        <div className="account-manager flex-3 flex-inital flex w-32 justify-around">
          {!user.isSignedIn && <SignInButton />}
          {user.isSignedIn && (
            <>
              <Link href="/account">account</Link>
              <UserButton />
            </>
          )}
        </div>
      </nav>
      <main className="bg-slate">{children}</main>
      <footer></footer>
    </>
  );
}
