import { SignInButton, useUser } from "@clerk/nextjs";
import Head from "next/head";
import Link from "next/link";
import { useRouter } from "next/router";
import { useEffect } from "react";
import ToggleTheme from "../shared/ToggleTheme";
import { useAppSelector } from "~/redux/hooks";

export default function PublicLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  const colorTheme = useAppSelector((state) => state.client.colorTheme);
  const user = useUser();

  const router = useRouter();
  const { isLoaded: userLoaded } = useUser();

  useEffect(() => {
    if (!userLoaded) return;
    if (user.isSignedIn) void router.push("/user/dashboard");
  }, [userLoaded]);

  return (
    <div className={`${colorTheme}`}>
      <Head>
        <title>Realty-Hub</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <nav className="flex">
        <div className="logo-container flex flex-none">
          <img className="logo"></img>
        </div>
        <div className="std-navigation flex flex-1 justify-around">
          <Link href="about">home</Link>
          <Link href="public/blog">blog</Link>
        </div>
        <div className="account-manager flex-3 flex-inital flex w-32 justify-around">
          <SignInButton />
        </div>
        <ToggleTheme />
      </nav>
      <main className="bg-bg100 dark:bg-darkBg100">{children}</main>
      <footer></footer>
    </div>
  );
}
