import { SignOutButton } from "@clerk/nextjs";
import Head from "next/head";
import Link from "next/link";
import ToggleTheme from "../shared/ToggleTheme";
import { useAppSelector } from "~/redux/hooks";

export default function UserLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  const colorTheme = useAppSelector((state) => state.client.colorTheme);

  return (
    <div className={`${colorTheme}`}>
      <Head>
        <title>Realty-Hub</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <nav className="flex">
        <div className="logo-container flex flex-none">
          <img className="logo"></img>
        </div>
        <div className="std-navigation flex flex-1 justify-around">
          <Link href="/user/dashboard">Dashboard</Link>
          <Link href="/user/calculators">Calculators</Link>
          <Link href="/user/blog">Blog</Link>
        </div>
        <div className="account-manager flex-3 flex-inital flex w-32 justify-around">
          <>
            <Link href="/user/account">account</Link>
            <SignOutButton />
          </>
        </div>
        <ToggleTheme />
      </nav>
      <main className="min-h-screen bg-bg100 dark:bg-darkBg100">
        {children}
      </main>
      <footer></footer>
    </div>
  );
}
